-- CREATE OR REPLACE PROCEDURE `adswerve-finance-reporting.Fin_Fcst_Module.OtherSales_V2`(Report_Period DATE)
-- BEGIN


DECLARE Report_Period DATE;
DECLARE PY_Start, NY_END DATE;
DECLARE TimePeriod, TimePeriod_WithDefaults, ThreeMonthTrail, SixMonthTrail, SQL1, SQL2, SQL3 STRING;


SET Report_Period = "2026-06-01"; --(SELECT `adswerve-finance.Fin_Routines.Fx_MaxRptPeriod`());
SET PY_Start = DATE(EXTRACT(YEAR FROM Report_Period)-1,1,1);
SET NY_END = DATE(EXTRACT(YEAR FROM Report_Period)+1,12,1);

SET TimePeriod =(
SELECT STRING_AGG(Timeline)
FROM( 
      SELECT CAST( FORMAT_DATE("'%b_%Y'",X) AS STRING) AS Timeline
      FROM UNNEST(
                  GENERATE_DATE_ARRAY(
                                        CAST(PY_Start AS DATE) 
                                        ,DATE_ADD(CAST(PY_Start AS DATE), INTERVAL 23 MONTH)
                                        ,INTERVAL 1 MONTH)  
                  ) AS X
    )
);

SET TimePeriod_WithDefaults = (
  SELECT STRING_AGG(
    'IFNULL(' || FORMAT_DATE('%b_%Y', X) || ', 0) AS ' ||  FORMAT_DATE('%b_%Y', X) 
  )
  FROM UNNEST(GENERATE_DATE_ARRAY(PY_Start, DATE_ADD(PY_Start, INTERVAL 23 MONTH), INTERVAL 1 MONTH)) AS X
);

---------------------------------------------------------------------------------------------------------
SET SQL1 = '''

CREATE OR REPLACE TABLE `adswerve-finance-reporting.Fin_Fcst_Module.OtherSales_V2` AS
SELECT 
  PARSE_DATE("%b_%Y", O.Period_F) AS Period
  ,O.* EXCEPT (Period_F)
FROM OtherSales O
ORDER BY 
    Period
''';
---------------------------------------------------------------------------------------------------------
SET SQL2 = '''
CREATE OR REPLACE TABLE `adswerve-finance-reporting.Fin_Fcst_Module.OtherSales_Pvt_V2` AS

WITH OS_Data AS (
SELECT 
  Period_F
  ,Parent_Nm
  ,Parent_ID
  ,Account
  --,LineItem  --Modified 7/9/2026
  ,Class  --Modified 7/9/2026
  ,AgencyOrMarketer
  ,IFNULL(FcstAmt,0) AS FcstAmt
FROM OtherSales 
)

,PVT AS (
SELECT
  *
FROM OS_Data
PIVOT(SUM(IFNULL(FcstAmt,0)) FOR Period_F IN (''' || TimePeriod || '''))
ORDER BY
    AgencyOrMarketer
    ,Parent_Nm
)

SELECT 
  Parent_Nm
  ,Parent_ID
  ,Account
  -- ,LineItem --Modified 7/9/2026
  ,Class --Modified 7/9/2026
  ,AgencyOrMarketer
  ,''' || TimePeriod_WithDefaults || '''
FROM PVT

''';
-- ---------------------------------------------------------------------------------------------------------



CREATE OR REPLACE TEMP TABLE OtherSales AS

WITH Periods AS(
SELECT 
    Period 
FROM UNNEST(
    GENERATE_DATE_ARRAY(PY_Start, NY_END, INTERVAL  1 MONTH)) AS Period
)

,Parents AS (
SELECT
  DISTINCT
  Parent_Nm
  ,Parent_ID
  ,AgencyOrMarketer
FROM `adswerve-finance.FinancialReporting.BI_NR_Dashboard`
WHERE
  EXTRACT(YEAR FROM Period) >= EXTRACT(YEAR FROM PY_Start)
  AND (
      REGEXP_CONTAINS(IS_Category,"Other Sales")
      OR REGEXP_CONTAINS(Account,"42500|51125") -- Chrome 12.23.2025
      OR REGEXP_CONTAINS(Account,"42700") --Snowflake
      OR REGEXP_CONTAINS(Account,"41600") --Audience
      OR REGEXP_CONTAINS(Account,"41400|41411|41412|41413|51170") --Amazon
      OR REGEXP_CONTAINS(Account,"41500|51175") --MediaMath
      OR REGEXP_CONTAINS(Account,"41197|51142") --LM Supply
      OR REGEXP_CONTAINS(Account,"51171") --Amazon Incentives
      OR REGEXP_CONTAINS(Account,"51176") --Media Math Incentives
      OR REGEXP_CONTAINS(Account,"42250|42251|51180") --Amplitude
      OR REGEXP_CONTAINS(Account,"51143") --Sovrn
      OR REGEXP_CONTAINS(Account,"51143") --Magnite


  )
  AND Parent_Nm <> ""
  AND Parent_Nm IS NOT NULL
)

-- ,Products AS(
-- SELECT
--   DISTINCT
--   MvA_LineItem
-- FROM `adswerve-finance.FinancialReporting.BI_NR_Dashboard`
-- WHERE
--   EXTRACT(YEAR FROM Period) >= EXTRACT(YEAR FROM PY_Start)
--   AND IS_Category = "Other Sales"
-- )

,Accounts AS(
SELECT
  DISTINCT
  Account
  ,Class
  --,MvA_LineItem AS LineItem
FROM `adswerve-finance.FinancialReporting.BI_NR_Dashboard`
WHERE
  EXTRACT(YEAR FROM Period) >= EXTRACT(YEAR FROM PY_Start)
  AND (
        ( 
            IS_Category = "Other Sales"
            AND REGEXP_CONTAINS(Account,"^4.*")
        )
        OR (
              REGEXP_CONTAINS(Account,"51150|51165|51199|51510|51515|51520")
              OR REGEXP_CONTAINS(Account,"42500|51125") -- Chrome 12.23.2025
              OR REGEXP_CONTAINS(Account,"42700") --Snowflake
              OR REGEXP_CONTAINS(Account,"41600") --Audience
              OR REGEXP_CONTAINS(Account,"41400|41411|41412|41413|51170") --Amazon
              OR REGEXP_CONTAINS(Account,"41500|51175") --MediaMath
              OR REGEXP_CONTAINS(Account,"41197|51142") --LM Supply
              OR REGEXP_CONTAINS(Account,"51171") --Amazon Incentives
              OR REGEXP_CONTAINS(Account,"51176") --Media Math Incentives
              OR REGEXP_CONTAINS(Account,"42250|42251|51180") --Amplitude
              OR REGEXP_CONTAINS(Account,"51143") --Sovrn
              OR REGEXP_CONTAINS(Account,"51143") --Magnite
           )
      )
  AND Parent_Nm <> ""
  AND Parent_Nm IS NOT NULL
  AND Period <= Report_Period
)


,Actuals AS (
SELECT
  Period
  ,Parent_Nm
  ,Parent_ID
  ,AgencyOrMarketer
  ,Class
  --,MvA_LineItem AS LineItem
  ,Account
  ,SUM(Amount_Net_CY) AS Amt_Net
FROM `adswerve-finance.FinancialReporting.BI_NR_Dashboard`
WHERE
  EXTRACT(YEAR FROM Period) >= EXTRACT(YEAR FROM PY_Start)
  AND (
        REGEXP_CONTAINS(IS_Category,"Other Sales")
        OR (
              REGEXP_CONTAINS(Account,"51150|51165|51199|51510|51515|51520")
              OR REGEXP_CONTAINS(Account,"42500|51125") -- Chrome 12.23.2025
              OR REGEXP_CONTAINS(Account,"42700") --Snowflake
              OR REGEXP_CONTAINS(Account,"41600") --Audience
              OR REGEXP_CONTAINS(Account,"41400|41411|41412|41413|51170") --Amazon
              OR REGEXP_CONTAINS(Account,"41500|51175") --MediaMath
              OR REGEXP_CONTAINS(Account,"41197|51142") --LM Supply
              OR REGEXP_CONTAINS(Account,"51171") --Amazon Incentives
              OR REGEXP_CONTAINS(Account,"51176") --Media Math Incentives
              OR REGEXP_CONTAINS(Account,"42250|42251|51180") --Amplitude
              OR REGEXP_CONTAINS(Account,"51143") --Sovrn
              OR REGEXP_CONTAINS(Account,"51143") --Magnite
        )
      )
  AND Parent_Nm <> ""
  AND Parent_Nm IS NOT NULL
  AND Period <= Report_Period
GROUP BY ALL
ORDER BY
  Parent_Nm
)

,Joiner AS(
SELECT
  P.Period
  ,PA.Parent_Nm
  ,PA.Parent_ID
  ,PA.AgencyOrMarketer
  ,Class
  --,A.LineItem
  ,A.Account
FROM Periods P
CROSS JOIN Parents PA
CROSS JOIN Accounts A
)


,LastMonth AS (
SELECT
  Period
  ,Account
  ,Parent_Nm
  ,Parent_ID
  ,Class
  --,LineItem
  ,Amt_Net
FROM Actuals 
WHERE
 Period = Report_Period
)

,Agg AS (
SELECT 
  J.Period
  ,FORMAT_DATE("%b_%Y",J.Period) AS Period_F
  ,J.Parent_Nm
  ,J.Parent_ID
  ,J.AgencyOrMarketer
  ,J.Class --Modified 7/9/2026
  --,J.LineItem --Modified 7/9/2026
  ,J.Account
  ,IFNULL(A.Amt_Net,0) AS Amt_Net
FROM Joiner J
LEFT JOIN Actuals A ON J.Period = A.Period
  AND J.Parent_ID = A.Parent_ID
  -- AND J.LineItem = A.LineItem
  AND J.Class = A.Class
  AND J.Account = A.Account

ORDER BY 
  J.Parent_Nm
  --,J.LineItem --Modified 7/9/2026
  ,J.Account
  ,J.Class
  ,J.Period
)

,AvgCalc AS (
SELECT 
  A.Period
  ,A.Period_F
  ,A.Parent_Nm
  ,A.Parent_ID
  ,AgencyOrMarketer
  -- ,A.LineItem --Modified 7/9/2026
  ,Class --Modified 7/9/2026
  ,A.Account
  ,A.Amt_Net
  ,ROUND(AVG(A.Amt_Net) OVER (  
      PARTITION BY A.Parent_ID, A.Account, A.Class    ORDER BY A.Period, A.Account, A.Class
      ROWS BETWEEN 2 PRECEDING AND CURRENT ROW
  ),2) AS Avg_3M
  -- ,ROUND(AVG(A.Amt_Net) OVER (  
  --     PARTITION BY A.Parent_ID, A.LineItem    ORDER BY A.Period
  --     ROWS BETWEEN 5 PRECEDING AND CURRENT ROW
  -- ),2) AS Avg_6M
FROM Agg A
)


-- SELECT * FROM AvgCalc
-- WHERE
--   REGEXP_CONTAINS(Account,"^4.*")




,Trended AS (
SELECT 
 C.Period
  ,C.Period_F
  ,C.Parent_Nm
  ,C.Parent_ID
  ,C.AgencyOrMarketer
  --,C.LineItem
  ,C,Class
  ,C.Account
  ,IFNULL(C.Amt_Net,0) AS Amt_Net
  ,IFNULL(C.Avg_3M,0) AS Avg_3M
  -- ,IFNULL(C.Avg_6M,0) AS Avg_6M
FROM AvgCalc C
WHERE
  C.Period = Report_Period
)


SELECT
--   A.Period
--   ,
  A.Period_F
  ,A.Parent_Nm
  ,A.Parent_ID
  ,A.Account
  --,A.LineItem --Modified 7/9/2026
  ,A.Class --Modified 7/9/2026
  ,A.AgencyOrMarketer
  ,A.Amt_Net AS Net_Actual
  ,CASE
    WHEN A.Period <= Report_Period THEN A.Amt_Net
    WHEN A.Period > Report_Period THEN L.Amt_Net --T.Avg_3M
    ELSE 0.99
   END AS FcstAmt
FROM Agg A
LEFT JOIN Trended T ON A.Parent_ID = T.Parent_ID
  -- AND A.LineItem = T.LineItem --Modified 7/9/2026
  AND A.Class = T.Class --Modified 7/9/2026
  AND A.Account = T.Account
-----------------------------------
--Modified 7/15/2025, 7/9/2026
LEFT JOIN LastMonth L ON 
  A.Parent_ID = L.Parent_ID
  -- AND A.LineItem = L.LineItem --Modified 7/9/2026
  AND A.Class = L.Class --Modified 7/9/2026
  AND A.Account = L.Account

-----------------------------------
GROUP BY ALL
HAVING SUM(FcstAmt) <>0
ORDER BY 
  A.Parent_Nm
  ,A.Account
  -- ,A.LineItem
  ,A.Class
  ,A.Period_F
;


EXECUTE IMMEDIATE SQL1;
EXECUTE IMMEDIATE SQL2;
SELECT * FROM `adswerve-finance-reporting.Fin_Fcst_Module.OtherSales_V2`

-- END;
