config {
  type: "operations",
  database: "adswerve-finance-reporting",
  schema: "Fin_Fcst_Module",
  name: "OtherSales_SaveFcst_V2"
}

CREATE OR REPLACE PROCEDURE `adswerve-finance-reporting.Fin_Fcst_Module.OtherSales_SaveFcst_V2`()
BEGIN

DECLARE SQL1, SQL2  STRING;
DECLARE Table_Nm1, Table_Nm2 STRING;

SET Table_Nm1 = CONCAT(
                      "adswerve-finance-reporting.Fin_Fcst_Module.OtherSales_SavedFcst_AgyMrk_V2_"--20240217");
                      ,FORMAT_TIMESTAMP("%Y%m%d",CURRENT_TIMESTAMP()));



SET SQL1 = CONCAT(
              "CREATE OR REPLACE TABLE ",
              Table_Nm1,''' AS 
              SELECT 
                *
              FROM  `adswerve-finance-reporting.Fin_Fcst_Module.OtherSales_FcstStage_AgyMrk_V2`
              WHERE
                Period IS NOT NULL;''');


EXECUTE IMMEDIATE SQL1;

END;